# File: .tekton/tasks.yml

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  description: This task cleans up the workspace before cloning new code.
  workspaces:
    - name: source
  steps:
    - name: clean
      image: alpine
      script: |
        echo "Starting cleanup of /workspace/source..."
        rm -rf /workspace/source/*
        echo "Cleanup complete."

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  description: This task runs linting and unit tests using flake8 and nose.
  workspaces:
    - name: source
  steps:
    - name: install-dependencies
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        pip install --upgrade pip
        pip install flake8 nose
    - name: run-lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: run-tests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        nosetests
